<a href="https://colab.research.google.com/github/gibranfp/CursoAprendizajeProfundo/blob/2027-1/notebooks/0_tensores_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensores en PyTorch
[PyTorch](https://pytorch.org/) es una biblioteca y marco de trabajo de código abierto que facilita la programación de redes neuronales profundas, ofreciendo varias funciones, clases y herramientas. En particular:

1. Definición de arreglos multidimensionales (clase `Tensor`) y operaciones entre ellos con soporte para GPUs y cómputo distribuido.
2. Diferenciación automática.
3. Interfaz modular con distintos niveles de abstracción para definir arquitecturas de redes neuronales y entrenarlas.
4. Clases y funciones para carga, generación de lotes y preprocesamiento de conjuntos de datos.

<img src="https://se.ewi.tudelft.nl/desosa2019/chapters/pytorch/images/pytorch/iGWbOXL.png" alt="Arquitectura de PyTorch" />

Fuente: [https://se.ewi.tudelft.nl/desosa2019/chapters/pytorch/](https://se.ewi.tudelft.nl/desosa2019/chapters/pytorch/)

## Clase `Tensor`
El objeto básico de PyTorch es el tensor, un arreglo multidimensional similar al `ndarray` de NumPy.

![](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-020-2649-2/MediaObjects/41586_2020_2649_Fig1_HTML.png)

Fuente: [Array programming with NumPy](https://www.nature.com/articles/s41586-020-2649-2).

En PyTorch, todo tensor es una instancia de la clase `Tensor` (o de alguna de sus subclases, como `nn.Parameter`). Un tensor no almacena directamente sus elementos, sino que contiene una referencia a un objeto de almacenamiento (un arreglo unidimensional y contiguo en memoria) junto con metadatos como:
 + El desplazamiento inicial dentro del almacenamiento (`storage_offset`)
 + La forma (`shape`)
 + El salto entre elementos consecutivos en cada dimensión (`stride`)
 + El tipo de dato de los elementos (`dtype`)
 + El dispositivo donde residen (`device`).

Debido a esta separación entre datos y metadatos, múltiples tensores pueden contener la referencia al mismo objeto de almacenamiento y diferir únicamente en sus metadatos. Diversas operaciones, como el cambio de forma, la transposición y los cortes, no copian los elementos, solo cambian los metadatos para tener una nueva vista sobre los mismos datos.

Adicionalmente, los tensores cuentan con métodos para realizar operaciones sobre ellos. La mayoría de estas operaciones están disponibles tanto en forma de función como de método, de modo que `torch.reshape(x, [3, 4])` y `x.reshape([3, 4])` son equivalentes. Por convención, los métodos cuyo nombre termina en guion bajo (por ejemplo, `add_`) modifican directamente el contenido del tensor, en lugar de devolver un tensor nuevo y dejar el original sin cambios.


In [1]:
import torch as th
import numpy as np

## Creación de tensores
### Función `tensor()`
Podemos definir un tensor a partir de valores específicos con la función `tensor()`. Para un escalar (tensor de grado 0) esto sería:

In [2]:
escalar = th.tensor(4.0)
print(f"Escalar: {escalar}, Tipo de variable: {type(escalar)}")

Escalar: 4.0, Tipo de variable: <class 'torch.Tensor'>


Un vector (tensor de grado 1):

In [3]:
vector = th.tensor([2.0, 3.0 , 4.0])
print(f"Vector: {vector}, Tipo de variable: {type(vector)}")

Vector: tensor([2., 3., 4.]), Tipo de variable: <class 'torch.Tensor'>


Una matriz (tensor de grado 2):

In [4]:
matriz = th.tensor([[2.0, 3.0, 4.0], [5.0, 6.0, 7.0]])
print(f"Matriz: {matriz}, Tipo de variable: {type(matriz)}")

Matriz: tensor([[2., 3., 4.],
        [5., 6., 7.]]), Tipo de variable: <class 'torch.Tensor'>


Un tensor de grado 3:

In [5]:
tensor3 = th.tensor([[[2.0, 3.0, 4.0], [5.0, 6.0, 7.0]], [[8.0, 9.0, 10.0], [11.0, 12.0, 13.0]]])
print(f"Tensor de grado 3: {tensor3}, Tipo de variable: {type(tensor3)}")

Tensor de grado 3: tensor([[[ 2.,  3.,  4.],
         [ 5.,  6.,  7.]],

        [[ 8.,  9., 10.],
         [11., 12., 13.]]]), Tipo de variable: <class 'torch.Tensor'>


Similar a NumPy, las instancias de `Tensor` tienen varios atributos, incluyendo el tipo de dato de cada elemento, el número de dimensiones, la forma y el número total de elementos.

In [6]:
print(f"Tipo de dato de cada elemento: {tensor3.dtype}")
print(f"Número de dimensiones: {tensor3.ndim}")
print(f"Forma del tensor: {tensor3.shape}")
print(f"Número total de elementos: {tensor3.numel()}")

Tipo de dato de cada elemento: torch.float32
Número de dimensiones: 3
Forma del tensor: torch.Size([2, 2, 3])
Número total de elementos: 12


PyTorch infiere el tipo de datos del tensor a partir de los valores de sus elementos. Sin embargo, se puede especificar a través del argumento `dtype`.

In [7]:
tenf64 = th.tensor([1,2], dtype=th.float64)
print(tenf64)

tensor([1., 2.], dtype=torch.float64)


### Tensores con ceros o unos
Otra forma de crear un tensor es con la función `zeros()`, que recibe como argumento la forma del tensor y regresa un tensor de esa forma con todos los elementos iguales a 0.

In [8]:
ceros = th.zeros((3, 4), dtype=th.float64)
print(ceros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


Una variación de la función anterior es `zeros_like()`, la cual hace lo mismo pero toma la forma y otras de sus propiedades (por ej. el tipo de datos) del tensor que se pasa como argumento.

In [9]:
ceros_l = th.zeros_like(ceros)
print(ceros_l)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


La función `ones()` es similar a la función`zeros()` pero en lugar de poner todos los valores a 0 los pone a 1.

In [10]:
unos = th.ones((3, 4))
print(unos)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


De forma análoga, `ones_like()` es una variación de esta última función que toma la forma y otras propiedades de otro tensor.

In [11]:
unos_l = th.ones_like(unos)
print(unos_l)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Tensores aleatorios
Podemos crear tensores con valores muestreados de distintas distribuciones. Por ej. para crear tensores con valores muestreados uniformemente en un rango de $[0,1)$, contamos con la función `rand`:

In [12]:
rnd = th.rand((3, 4))
print(rnd)

tensor([[0.6153, 0.0465, 0.1106, 0.2640],
        [0.6181, 0.9740, 0.6755, 0.2307],
        [0.3665, 0.4257, 0.5882, 0.6656]])


Usando los tensores generados por `rand` y `rand_like` es posible generar tensores con valores muestreados de una uniforme en un rango $[a, b)$ de la siguiente manera:

In [13]:
a = -5
b = 3
unifab = th.rand((3, 4)) * (b - a) + a
print(unifab)

tensor([[-1.3831, -3.4899,  0.0868,  0.9461],
        [ 0.5136, -0.6359, -0.4682,  0.2054],
        [ 0.4770,  0.9638, -4.4681, -4.0618]])


Alternativamente, podemos instanciar una clase `Tensor` pasando el tamaño como argumento al constructor y llamando al método `uniform_`

In [14]:
print(th.Tensor(3, 4).uniform_(-5, 3))

tensor([[-4.8152,  1.5962, -0.0272,  1.3899],
        [ 1.9360,  2.2778, -1.6560, -4.7306],
        [-0.3347,  2.2272, -4.0504,  1.8603]])


Para valores enteros muestreados uniformemente tenemos las funciones `randint` y `randint_like`.

In [15]:
randint = th.randint(low=-3, high= 5, size= (3, 4))
randint_l = th.randint_like(randint, low=-3, high= 5)
print(f"randint(): {randint}, randint_like(): {randint_l}")

randint(): tensor([[-2,  2, -1, -2],
        [ 1,  2, -1, -1],
        [ 2,  2,  1,  2]]), randint_like(): tensor([[ 2,  3, -1, -1],
        [ 2, -1,  0, -2],
        [ 1, -1,  3,  4]])


De forma similar, la función `randn` genera tensores con valores muestreados de una normal con media 0 y desviación estándar 1.

In [16]:
randn = th.randn((3,4))
print(randn)

tensor([[ 0.6355,  0.7758, -0.9208, -0.6802],
        [-1.2450, -0.9753,  1.7855, -0.5354],
        [ 1.4859, -0.8578, -0.3467, -0.4125]])


Con los tensores generados por `randn` podemos generar tensores cuyos valores sean muestreados de una normal con distinta media y desviación estándar de la siguiente manera:

In [17]:
std = 10
mu = -5

randn2 = th.randn((3, 4)) * std + mu
print(randn2)

tensor([[-13.3617, -24.1921,  -5.6846,   7.2586],
        [ -1.5345, -10.2150,  -5.7398, -21.7702],
        [  6.2143,  -3.1595,  -5.7186,   1.5505]])


También podemos generar tensores con valores muestreados de una normal con media y desviación estándar arbitraria usando la función `normal`.

In [18]:
norm = th.normal(mean = -5, std = 10, size= (3, 4))
print(norm)

tensor([[ -7.8134,  -3.3053,  -1.4415,  -8.9205],
        [-15.3348, -14.7462, -10.4975,  -2.3183],
        [ -9.4524,   2.9627,  -3.1430,   9.7410]])


Si deseamos generar tensores muestreados de una distribución multinomial podemos usar la función `multinomial`, a la cual deben especificarse las probabilidades de cada clase como un tensor de grado 1 y el número de muestras.

In [19]:
multi = th.multinomial(th.tensor([0.1, 0.2, 0.7]), num_samples=100, replacement=True)
print(multi)

tensor([2, 2, 2, 1, 1, 2, 1, 0, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 0, 2, 2,
        1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2,
        2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 1, 2,
        2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2,
        2, 2, 2, 2])


El número de clases depende del tamaño del tensor y el argumento `replacement` define si las muestras son con o sin reemplazo (en este último caso el número de muestras debe ser menor o igual al número de clases).

### Funciones `arange` y `linspace`
Por otra parte, la función `arange()` genera una secuencia de números (como el `range()` de Python):

In [20]:
rango = th.arange(start=-3, end=5, step=0.5)
print(rango)

tensor([-3.0000, -2.5000, -2.0000, -1.5000, -1.0000, -0.5000,  0.0000,  0.5000,
         1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000])


De manera similar, la función `linspace()` genera tensores con valores con el mismo espaciado en un intervalo.



In [21]:
ls = th.linspace(start=-3, end=5, steps=20)
print(ls)

tensor([-3.0000, -2.5789, -2.1579, -1.7368, -1.3158, -0.8947, -0.4737, -0.0526,
         0.3684,  0.7895,  1.2105,  1.6316,  2.0526,  2.4737,  2.8947,  3.3158,
         3.7368,  4.1579,  4.5789,  5.0000])


## Tipos

Los elementos de los tensores pueden ser de distintos tipos básicos y precisiones. Por ejemplo, flotantes de 64, 32 o 16 bits (`float64`, `float32`, `float16`) o enteros con y sin signo de distintos tamaños (`int32`, `uint8`). La elección del tipo determina tanto la memoria que ocupa cada elemento como la precisión y el rango de los valores que puede representar (`uint8` solo representa enteros de 0 a 255, las operaciones que exceden ese rango se desbordan).

In [22]:
tensor_f64 = th.arange(start=-1, end=1, step=0.1, dtype=th.float64)
tensor_i32 = th.arange(start=-10, end=10, step=1, dtype=th.int32)
tensor_f16 = th.arange(start=-1, end=1, step=0.1, dtype=th.float16)
tensor_u8 = th.arange(start=0, end=256, step=32, dtype=th.uint8)

print(f'float64: {tensor_f64}')
print(f'int32: {tensor_i32}')
print(f'float16: {tensor_f16}')
print(f'uint8: {tensor_u8}\n')

print(f'Bytes por elemento: float64={tensor_f64.element_size()}, '
      f'int32={tensor_i32.element_size()}, float16={tensor_f16.element_size()}, '
      f'uint8={tensor_u8.element_size()}')

print(f'255 + 1 en uint8: {th.tensor([255], dtype=th.uint8) + th.tensor([1], dtype=th.uint8)}')

float64: tensor([-1.0000e+00, -9.0000e-01, -8.0000e-01, -7.0000e-01, -6.0000e-01,
        -5.0000e-01, -4.0000e-01, -3.0000e-01, -2.0000e-01, -1.0000e-01,
         5.5511e-17,  1.0000e-01,  2.0000e-01,  3.0000e-01,  4.0000e-01,
         5.0000e-01,  6.0000e-01,  7.0000e-01,  8.0000e-01,  9.0000e-01],
       dtype=torch.float64)
int32: tensor([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,
          4,   5,   6,   7,   8,   9], dtype=torch.int32)
float16: tensor([-1.0000, -0.8999, -0.7998, -0.7002, -0.6001, -0.5000, -0.3999, -0.3000,
        -0.2000, -0.1000,  0.0000,  0.1000,  0.2000,  0.3000,  0.3999,  0.5000,
         0.6001,  0.7002,  0.7998,  0.8999], dtype=torch.float16)
uint8: tensor([  0,  32,  64,  96, 128, 160, 192, 224], dtype=torch.uint8)

Bytes por elemento: float64=8, int32=4, float16=2, uint8=1
255 + 1 en uint8: tensor([0], dtype=torch.uint8)


Nota que el valor que debería ser 0 aparece como `5.5511e-17`. Esto se debe al error de redondeo acumulado en los pasos de `arange`. Por esta razón, en ocasiones es conveniente comparar flotantes usando las funciones `th.allclose` o `th.isclose`, en lugar del operador `==`.

También se pueden convertir de tipos con el método `type()`:

In [23]:
print(tensor_i32.type(th.float64).dtype)
print(tensor_f64.type(th.float32).dtype)

torch.float64
torch.float32


## Índices
Los índices de los tensores siguen reglas similares a los arreglos de NumPy y las listas de Python.

In [24]:
ten_ind = th.reshape(th.linspace(start=10, end=-10, steps=30), [6, 5])
print(f"Primer renglón: {ten_ind[0].numpy()}")
print(f"Tercer renglón: {ten_ind[2].numpy()}")
print(f"Último renglón: {ten_ind[-1].numpy()}")

print(f"Primer columna: {ten_ind[:, 0].numpy()}")
print(f"Última columna: {ten_ind[:, -1].numpy()}")

Primer renglón: [10.         9.310345   8.620689   7.9310346  7.2413793]
Tercer renglón: [3.1034482 2.413793  1.7241378 1.0344826 0.3448274]
Último renglón: [ -7.2413793  -7.9310346  -8.620689   -9.310345  -10.       ]
Primer columna: [10.         6.551724   3.1034482 -0.3448274 -3.7931032 -7.2413793]
Última columna: [  7.2413793   3.7931032   0.3448274  -3.1034482  -6.551724  -10.       ]


Los tensores de PyTorch también permiten _slicing_.

In [25]:
print(f"Todos los renglones: {ten_ind[:].numpy()}")
print(f"Renglones antes del 3: {ten_ind[:3].numpy()}")
print(f"Renglones del 4 al final: {ten_ind[4:].numpy()}")
print(f"Renglones del 3 al 5: {ten_ind[3:6].numpy()}")
print(f"Cada dos renglones: {ten_ind[::2].numpy()}")

Todos los renglones: [[ 10.          9.310345    8.620689    7.9310346   7.2413793]
 [  6.551724    5.862069    5.172414    4.4827585   3.7931032]
 [  3.1034482   2.413793    1.7241378   1.0344826   0.3448274]
 [ -0.3448274  -1.0344826  -1.7241378  -2.413793   -3.1034482]
 [ -3.7931032  -4.4827585  -5.172414   -5.862069   -6.551724 ]
 [ -7.2413793  -7.9310346  -8.620689   -9.310345  -10.       ]]
Renglones antes del 3: [[10.         9.310345   8.620689   7.9310346  7.2413793]
 [ 6.551724   5.862069   5.172414   4.4827585  3.7931032]
 [ 3.1034482  2.413793   1.7241378  1.0344826  0.3448274]]
Renglones del 4 al final: [[ -3.7931032  -4.4827585  -5.172414   -5.862069   -6.551724 ]
 [ -7.2413793  -7.9310346  -8.620689   -9.310345  -10.       ]]
Renglones del 3 al 5: [[ -0.3448274  -1.0344826  -1.7241378  -2.413793   -3.1034482]
 [ -3.7931032  -4.4827585  -5.172414   -5.862069   -6.551724 ]
 [ -7.2413793  -7.9310346  -8.620689   -9.310345  -10.       ]]
Cada dos renglones: [[10.         9.3

A diferencia de los arreglos de NumPy, en las instancias de `Tensor` no es posible que el paso de los índices sea negativo. Para invertir el orden de los elementos a lo largo de uno o más dimensiones se utiliza la función `flip`, que recibe el tensor y la lista de dimensiones a invertir.

In [26]:
# NumPy
nparr = np.arange(start=0, stop=10, step=1)
print(f'NumPy con paso negativo: {nparr[::-1]}')

# PyTorch
tharr = th.arange(start=0, end=10, step=1)
try:
  print(tharr[::-1])
except ValueError as err:
  print(f'PyTorch con paso negativo: {err}')

# La alternativa en PyTorch es la función flip, que recibe las dimensiones a invertir
print(f'PyTorch con flip: {th.flip(tharr, dims=[0])}')

NumPy con paso negativo: [9 8 7 6 5 4 3 2 1 0]
PyTorch con paso negativo: step must be greater than zero
PyTorch con flip: tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


Las comparaciones entre tensores se realizan elemento a elemento y producen un tensor booleano (máscara) con la misma forma, el cual puede usarse como índice de otros tensores. Cuando usamos la máscara como índice de otro tensor, el resultado es un tensor de grado 1 con los elementos donde la máscara es verdadera.

In [27]:
X = th.randn(3, 4)
mascara = X > 0

print(f'X = {X}')
print(f'Máscara: {mascara}, tipo: {mascara.dtype}')
print(f'Elementos positivos: {X[mascara]}, forma: {X[mascara].shape}')
print(f'¿Es una vista?: {X[mascara].data_ptr() == X.data_ptr()}')
print(f'Número de positivos: {mascara.sum()}')
print(f'¿Hay algún positivo?: {mascara.any()}, ¿todos lo son?: {mascara.all()}')

X = tensor([[-0.2422, -0.2387, -0.2620, -0.8245],
        [-0.8339, -0.1691, -1.4822, -0.9435],
        [ 0.9150,  0.3938,  1.9780, -0.2239]])
Máscara: tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True, False]]), tipo: torch.bool
Elementos positivos: tensor([0.9150, 0.3938, 1.9780]), forma: torch.Size([3])
¿Es una vista?: False
Número de positivos: 3
¿Hay algún positivo?: True, ¿todos lo son?: False


Una alternativa es la función `where`, la cual recibe una máscara y dos tensores. La función devuelve un tensor cuyos elementos se toman del primer tensor donde la máscara es verdadera y del segundo donde es falsa.

In [28]:
X = th.randn(3, 4)

print(f'X = {X}')
print(f'Máscara X > 0 = {X > 0}')
print(f'Selección con máscara: X[X > 0] -> forma {X[X > 0].shape}')
print(f'Con where: {th.where(X > 0, X, 0.)}')

X = tensor([[ 1.2220, -0.0331, -0.3787, -1.2462],
        [ 0.3499,  0.9362,  0.7788, -0.1273],
        [-0.5275, -0.0187,  0.0269,  0.2016]])
Máscara X > 0 = tensor([[ True, False, False, False],
        [ True,  True,  True, False],
        [False, False,  True,  True]])
Selección con máscara: X[X > 0] -> forma torch.Size([6])
Con where: tensor([[1.2220, 0.0000, 0.0000, 0.0000],
        [0.3499, 0.9362, 0.7788, 0.0000],
        [0.0000, 0.0000, 0.0269, 0.2016]])


Además, podemos iterar sobre los elementos de un tensor:

In [29]:
for x in randint:
  print(x)

for x in randint:
  for e in x:
    print(e)

tensor([-2,  2, -1, -2])
tensor([ 1,  2, -1, -1])
tensor([2, 2, 1, 2])
tensor(-2)
tensor(2)
tensor(-1)
tensor(-2)
tensor(1)
tensor(2)
tensor(-1)
tensor(-1)
tensor(2)
tensor(2)
tensor(1)
tensor(2)


## Formas
La forma de los tensores se puede cambiar, siempre y cuando se mantenga el mismo número de elementos totales.

![](https://www.tensorflow.org/guide/images/tensor/reshape-before.png)
![](https://www.tensorflow.org/guide/images/tensor/reshape-good1.png)
![](https://www.tensorflow.org/guide/images/tensor/reshape-good2.png)

Fuente: Tutorial [_Introduction to Tensors_](https://www.tensorflow.org/guide/tensor) de Tensorflow

In [30]:
x_orig = th.arange(30)
print(x_orig)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])


Nota que es necesario asegurarse de que, al cambiar la forma, el número total de elementos sea el mismo. Por ejemplo, si tenemos 30 elementos, solo podemos cambiar a formas en las que el producto de todas las dimensiones sea igual a 30 ($5 \times 6$, $6 \times 5$, $3 \times 10$, $10 \times 3$, $1 \times 30$, $30 \times 1$, $1 \times 1 \times 30$, $5 \times 1 \times 6$, etc.).

Para cambiar la forma de este vector usamos la función (o el método) `reshape()`.

In [31]:
x_forma2 = th.reshape(x_orig, [3, 2, 5])
x_forma3 = th.reshape(x_orig, [3, 10])
x_forma4 = th.reshape(x_orig, [6, 5])
x_forma5 = th.reshape(x_orig, [2, 3, 5])
x_forma6 = th.reshape(x_orig, [5, 3, 2])

Examinemos sus formas:

In [32]:
print(f"Forma de x_orig: {x_orig.shape}")
print(f"Forma de x_forma2: {x_forma2.shape}")
print(f"Forma de x_forma3: {x_forma3.shape}")
print(f"Forma de x_forma4: {x_forma4.shape}")
print(f"Forma de x_forma5: {x_forma5.shape}")
print(f"Forma de x_forma6: {x_forma6.shape}")

Forma de x_orig: torch.Size([30])
Forma de x_forma2: torch.Size([3, 2, 5])
Forma de x_forma3: torch.Size([3, 10])
Forma de x_forma4: torch.Size([6, 5])
Forma de x_forma5: torch.Size([2, 3, 5])
Forma de x_forma6: torch.Size([5, 3, 2])


Si solo requerimos agregar una dimensión, además de la función `reshape` podemos usar `unsqueeze`, la cual toma como argumento un tensor y un dimensión y regresa un tensor con los mismos elementos pero con una dimensión agregada.

In [33]:
print(f'Tensor original de: {x_forma3.shape}')
print(f'Dimensión 0: {th.unsqueeze(x_forma3, dim=0).shape}')
print(f'Dimensión 1: {th.unsqueeze(x_forma3, dim=1).shape}')
print(f'Dimensión 2: {th.unsqueeze(x_forma3, dim=2).shape}')

Tensor original de: torch.Size([3, 10])
Dimensión 0: torch.Size([1, 3, 10])
Dimensión 1: torch.Size([3, 1, 10])
Dimensión 2: torch.Size([3, 10, 1])


Para quitar dimensiones de tamaño 1 se puede utilizar la función `squeeze`.

In [34]:
x_exp4 = th.unsqueeze(x_forma3, dim=2)
x_exp4 = th.unsqueeze(x_exp4, dim=0)

print(f'Tensor de 4: {x_exp4.shape}')
print(f'Aplicando squeeze: {th.squeeze(x_exp4).shape}')
print(f'Aplicando squeeze sobre dimensión 1: {th.squeeze(x_exp4, dim=1).shape}')

Tensor de 4: torch.Size([1, 3, 10, 1])
Aplicando squeeze: torch.Size([3, 10])
Aplicando squeeze sobre dimensión 1: torch.Size([1, 3, 10, 1])


Como habíamos mencionado, cuando realizamos algunas operaciones, como redimensionar con `reshape`, no se está creando una copia de los datos, sino que solo se modifican los metadatos. Por otro lado, la asignación con `=` tampoco crea una copia, únicamente asigna otro nombre al mismo tensor. En ambos casos, al modificar los elementos a través de cualquiera de ellos el cambio se refleja en el otro.

In [35]:
x_orig2 = x_orig
x_orig2[5] = 1000

print(f"Original: {x_orig}")
print(f"Asignación de original: {x_orig2}")
print(f"x_forma2: {x_forma2}")
print(f"x_forma3: {x_forma3}")

Original: tensor([   0,    1,    2,    3,    4, 1000,    6,    7,    8,    9,   10,   11,
          12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
          24,   25,   26,   27,   28,   29])
Asignación de original: tensor([   0,    1,    2,    3,    4, 1000,    6,    7,    8,    9,   10,   11,
          12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
          24,   25,   26,   27,   28,   29])
x_forma2: tensor([[[   0,    1,    2,    3,    4],
         [1000,    6,    7,    8,    9]],

        [[  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29]]])
x_forma3: tensor([[   0,    1,    2,    3,    4, 1000,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29]])


Para crear una copia de los datos es necesario usar el método `clone()`.

In [36]:
x_orig_clone = x_orig.clone()
x_orig[3] = -1

print(f"Original: {x_orig}")
print(f"Clonado: {x_orig_clone}")

Original: tensor([   0,    1,    2,   -1,    4, 1000,    6,    7,    8,    9,   10,   11,
          12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
          24,   25,   26,   27,   28,   29])
Clonado: tensor([   0,    1,    2,    3,    4, 1000,    6,    7,    8,    9,   10,   11,
          12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
          24,   25,   26,   27,   28,   29])


## PyTorch y NumPy
Los tensores de PyTorch se pueden convertir a arreglos de NumPy y viceversa.

In [37]:
nparr = np.ones((2, 5))

De arreglo de NumPy a un tensor de PyTorch tenemos tres opciones, que difieren tanto en el tipo de dato del resultado como en el manejo de la memoria.
  1. `tensor`: copia los datos y conserva el tipo del arreglo.
  2. Constructor de `Tensor`: copia los datos pero convierte el tipo a `float32`.
  3. `from_numpy`: no copia los datos, sino que construye un tensor que comparte el mismo almacenamiento que el arreglo.

In [38]:
npten_func = th.tensor(nparr)  # copia, conserva float64
npten_clase = th.Tensor(nparr) # copia, convierte a float32
npten_from = th.from_numpy(nparr) # comparte memoria con nparr

print(f'NumPy: tipo={nparr.dtype}, mem={nparr.__array_interface__['data'][0]}')
print(f'tensor: tipo={npten_func.dtype}, mem={npten_func.data_ptr()}')
print(f'Tensor: tipo={npten_clase.dtype}, mem={npten_clase.data_ptr()}')
print(f'from_numpy: tipo={npten_from.dtype}, mem={npten_from.data_ptr()}')

NumPy: tipo=float64, mem=354861056
tensor: tipo=torch.float64, mem=330233984
Tensor: tipo=torch.float32, mem=437744064
from_numpy: tipo=torch.float64, mem=354861056


Debido a que `from_numpy` comparte el almacenamiento, cualquier modificación de los elementos del arreglo se refleja en el tensor y viceversa. Esta conversión es válida únicamente para arreglos y tensores que se encuentran en CPU.

Para convertir un tensor a un arreglo de NumPy, contamos con el método `numpy` de cualquier instancia de `Tensor`. Al igual que `from_numpy`, el arreglo resultante comparte el almacenamiento con el tensor. Para obtener un arreglo independiente es necesario copiar los datos explícitamente, ya sea con el método `copy()` de NumPy sobre el arreglo resultante (`t.numpy().copy()`) o con el método `clone()` de PyTorch sobre el tensor original (`t.clone().numpy()`).

In [39]:
tenarr = th.ones(5)
tennp_vista = tenarr.numpy()
tennp_copia = tenarr.numpy().copy()
tennp_clona = tenarr.clone().numpy()

print(f'Tensor: mem={tenarr.data_ptr()}')
print(f'numpy(): mem={tennp_vista.__array_interface__["data"][0]}')
print(f'numpy().copy(): mem={tennp_copia.__array_interface__["data"][0]}')
print(f'clone().numpy(): mem={tennp_clona.__array_interface__["data"][0]}')

Tensor: mem=437789760
numpy(): mem=437789760
numpy().copy(): mem=429394528
clone().numpy(): mem=330233152


## Operaciones básicas
PyTorch cuenta con operadores y funciones básicas para los tensores, similares a las de NumPy, entre ellas operadores elemento a elemento, multiplicación de tensores, etc.

### Elemento a elemento
Estas operaciones se aplican entre dos tensores de formas compatibles, siendo el caso más simple el de dos tensores de la misma forma. La salida es un tensor de esa misma forma, en el que cada elemento se obtiene aplicando la operación especificada entre el elemento correspondiente de un tensor y el del otro. Entre estas operaciones se encuentran la suma, la resta, la multiplicación, la división y la potenciación, entre otras.

In [40]:
x = th.tensor([[1., 2., 3.]])
y = th.tensor([[3., 4., 5.]])

print(f'x = {x}')
print(f'y = {y}')
print(f'10 * x = {10 * x}')
print(f'x + y = {x + y}')
print(f'x - y = {x - y}')
print(f'x * y = {x * y}')
print(f'x / y = {x / y}')
print(f'x^y = {x**y}')
print(f'x^2 = {x**2}')

x = tensor([[1., 2., 3.]])
y = tensor([[3., 4., 5.]])
10 * x = tensor([[10., 20., 30.]])
x + y = tensor([[4., 6., 8.]])
x - y = tensor([[-2., -2., -2.]])
x * y = tensor([[ 3.,  8., 15.]])
x / y = tensor([[0.3333, 0.5000, 0.6000]])
x^y = tensor([[  1.,  16., 243.]])
x^2 = tensor([[1., 4., 9.]])


Para realizar las operaciones elemento a elemento en PyTorch, las formas de ambos tensores deben ser iguales o bien compatibles. Para determinarlo, se comparan dimensión a dimensión desde la última hacia atrás, verificando que las dos dimensiones sean iguales, que alguna valga 1 o que alguna no exista. Si esto se cumple para todas las dimensiones de las dos formas, se realiza la difusión ([_broadcasting_](https://pytorch.org/docs/stable/notes/broadcasting.html)): cada dimensión de tamaño 1 o ausente se repite para igualar el tamaño del otro tensor.

Por ejemplo, al sumar la matriz `a` de forma `(4,3)` con el vector `b` de forma `(3,)`, el tamaño de la última dimensión coincide (3 y 3) y la primera está ausente en `b`, por lo que las formas son compatibles. Al realizar la suma, se difunde el vector `b` a lo largo de los cuatro renglones de la matriz `a`:

In [41]:
a = th.rand(4, 3)
b = th.arange(1., 4.)

print(f'a = {a}')
print(f'b = {b}')
print(f'a + b = {(a + b)}')
print(f'Formas: a={a.shape}, b={b.shape}, a+b={(a + b).shape}')

a = tensor([[0.7823, 0.6284, 0.5058],
        [0.8006, 0.0096, 0.9984],
        [0.3465, 0.5404, 0.3914],
        [0.8389, 0.7357, 0.1887]])
b = tensor([1., 2., 3.])
a + b = tensor([[1.7823, 2.6284, 3.5058],
        [1.8006, 2.0096, 3.9984],
        [1.3465, 2.5404, 3.3914],
        [1.8389, 2.7357, 3.1887]])
Formas: a=torch.Size([4, 3]), b=torch.Size([3]), a+b=torch.Size([4, 3])


Asimismo, al sumar la matriz `a` de forma `(4,3)` con la matriz columna `c` de forma `(4,1)`, la última dimensión es de tamaño 1 en `c` y la primera coincide (4 y 4), por lo que las formas también son compatibles. En este caso, al sumar ambos tensores, se difunde `c` a lo largo de las tres columnas de la matriz `a`:

In [42]:
c = th.rand(4, 1)
d = th.arange(-4., 0.)

print(f'a = {a}')
print(f'c = {c}')
print(f'a + c = {(a + c)}')
print(f'Formas: a={a.shape}, c={c.shape}, a+c={(a + c).shape}')

a = tensor([[0.7823, 0.6284, 0.5058],
        [0.8006, 0.0096, 0.9984],
        [0.3465, 0.5404, 0.3914],
        [0.8389, 0.7357, 0.1887]])
c = tensor([[0.2334],
        [1.0000],
        [0.9780],
        [0.3484]])
a + c = tensor([[1.0157, 0.8618, 0.7392],
        [1.8006, 1.0096, 1.9984],
        [1.3245, 1.5184, 1.3694],
        [1.1873, 1.0841, 0.5371]])
Formas: a=torch.Size([4, 3]), c=torch.Size([4, 1]), a+c=torch.Size([4, 3])


Un caso particular se presenta al sumar la matriz columna `c` de forma `(4,1)` con el vector `b` de forma `(3,)`. La última dimensión es de tamaño 1 en `c` y de tamaño 3 en `b`, por lo que sus formas son compatibles. Sin embargo, en este caso la difusión se aplica a ambos tensores a la vez: `c` se repite a lo largo de las tres columnas y `b` a lo largo de los cuatro renglones. El resultado es una matriz de forma `(4,3)`.

In [43]:
print(f'b = {b}')
print(f'c = {c}')
print(f'b + c = {(b + c)}')
print(f'Formas: b={b.shape}, c={c.shape}, b+c={(b + c).shape}')

b = tensor([1., 2., 3.])
c = tensor([[0.2334],
        [1.0000],
        [0.9780],
        [0.3484]])
b + c = tensor([[1.2334, 2.2334, 3.2334],
        [2.0000, 3.0000, 4.0000],
        [1.9780, 2.9780, 3.9780],
        [1.3484, 2.3484, 3.3484]])
Formas: b=torch.Size([3]), c=torch.Size([4, 1]), b+c=torch.Size([4, 3])


En cambio, al sumar la matriz `a` de forma `(4,3)` con el vector `d` de forma `(4,)`, la última dimensión es de tamaño 3 en `a` y de tamaño 4 en `d`, por lo que las formas no son compatibles y la operación produce un error. Aunque el tamaño de `d` es igual al número de renglones de `a`, la suma no se puede realizar por renglón debido a que la comparación empieza por la última dimensión (no por la primera). Para realizar la operación por renglón, sería necesario cambiar la forma de `d` a `(4,1)`.

In [44]:
try:
  a + d
except RuntimeError as err:
  print(f'a + d: {err}')

print(f'a + d.unsqueeze(1) = {a + d.unsqueeze(1)}')
print(f'Formas: a={a.shape}, d.unsqueeze(1)={d.unsqueeze(1).shape}, a+d.unsqueeze(1)={(a + d.unsqueeze(1)).shape}')

a + d: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1
a + d.unsqueeze(1) = tensor([[-3.2177, -3.3716, -3.4942],
        [-2.1994, -2.9904, -2.0016],
        [-1.6535, -1.4596, -1.6086],
        [-0.1611, -0.2643, -0.8113]])
Formas: a=torch.Size([4, 3]), d.unsqueeze(1)=torch.Size([4, 1]), a+d.unsqueeze(1)=torch.Size([4, 3])


Es importante tener presentes las reglas de la difusión y verificar las formas de los tensores al realizar una operación, pues de lo contrario se pueden obtener resultados incorrectos sin advertirlo. Por ejemplo, al realizar una operación con un tensor de forma `(n,)` y otro de forma `(n,1)`, el
resultado es una matriz de forma `(n,n)` y no un vector columna de forma `(n,1)`, como podría esperarse. Debido a que la operación no produce error ni advertencia alguna, el resultado puede propagarse a través de operaciones posteriores si sus formas son compatibles. En esos casos, el problema llega a manifestarse después de haberse originado, lo que dificulta su detección y localización.

In [45]:
print(f'c = {c}')
print(f'd = {d}')
print(f'c + d = {(c + d)}')
print(f'Formas: c={c.shape}, d={d.shape}, c+d={(c + d).shape}')

c = tensor([[0.2334],
        [1.0000],
        [0.9780],
        [0.3484]])
d = tensor([-4., -3., -2., -1.])
c + d = tensor([[-3.7666e+00, -2.7666e+00, -1.7666e+00, -7.6660e-01],
        [-3.0000e+00, -2.0000e+00, -1.0000e+00, -6.3181e-06],
        [-3.0220e+00, -2.0220e+00, -1.0220e+00, -2.1983e-02],
        [-3.6516e+00, -2.6516e+00, -1.6516e+00, -6.5165e-01]])
Formas: c=torch.Size([4, 1]), d=torch.Size([4]), c+d=torch.Size([4, 4])


Para consultar la forma del resultado sin realizar la operación, se emplea la función `broadcast_shapes`.

In [46]:
print(f'formas (4x1) y (3,) -> {th.broadcast_shapes((4,1), (3,))}')

formas (4x1) y (3,) -> torch.Size([4, 3])


### Transpuesta y concatenación
Es posible obtener la transpuesta de una matriz con la función `transpose`, que recibe el tensor y las dos dimensiones que se desean intercambiar (`th.transpose(M, 0, 1)`) o con el atributo `.T` de cualquier matriz instancia de `Tensor`.

In [47]:
Mtr1 = th.rand((4,3))
Mtr2 = th.rand((3,2))

print(f'Transpuesta de x: {th.transpose(x, 1, 0).shape}')
print(f'Transpuesta de y: {y.T.shape}')
print(f'Transpuesta de M1: {th.transpose(Mtr1, 1, 0).shape}')
print(f'Transpuesta de M2: {Mtr2.T.shape}')

Transpuesta de x: torch.Size([3, 1])
Transpuesta de y: torch.Size([3, 1])
Transpuesta de M1: torch.Size([3, 4])
Transpuesta de M2: torch.Size([2, 3])


 Cuando se requiere reordenar más de dos dimensiones se utiliza `permute`, que recibe los índices de todos las dimensiones en el orden deseado.

In [48]:
Mp = th.rand((3,2,4))

print(f'Forma Mp = {Mp.shape}')
print(f'Permutación (0,2,1) = {th.permute(Mp, [2, 0, 1]).shape}')

Forma Mp = torch.Size([3, 2, 4])
Permutación (0,2,1) = torch.Size([4, 3, 2])


También podemos concatenar (función `concat`) una lista de tensores (primer argumento) sobre una dimensión específico (argumento `dim` o `axis`).

In [49]:
Mcat1 = th.rand((3,2))
Mcat2 = th.rand((2,3))
print(f'x={x.shape}, y={y.shape}, M1={Mcat1}, M2={Mcat2}\n')
print(f'Concatenación de 2 vectores sobre dimensión 0: {th.concat([x, y], dim=0).shape}')
print(f'Concatenación de 2 vectores sobre dimensión 1: {th.concat([x, y], dim=1).shape}')
print(f'Concatenación de 2 matrices sobre dimensión 0: {th.concat([Mcat1, Mcat2.T], dim=0).shape}') # no funciona sin transpuesta
print(f'Concatenación de 2 matrices sobre dimensión 1: {th.concat([Mcat1.T, Mcat2], dim=1).shape}')

x=torch.Size([1, 3]), y=torch.Size([1, 3]), M1=tensor([[0.3786, 0.9900],
        [0.6044, 0.6676],
        [0.7351, 0.8665]]), M2=tensor([[0.6490, 0.2446, 0.2115],
        [0.4188, 0.7560, 0.1182]])

Concatenación de 2 vectores sobre dimensión 0: torch.Size([2, 3])
Concatenación de 2 vectores sobre dimensión 1: torch.Size([1, 6])
Concatenación de 2 matrices sobre dimensión 0: torch.Size([6, 2])
Concatenación de 2 matrices sobre dimensión 1: torch.Size([2, 6])


De forma similar, es posible apilar tensores sobre una dimensión usando la función `stack` (el tensor resultante es un grado mayor al de los tensores de argumento, los cuales tienen la misma forma).

In [50]:
v1 = th.rand([5])
v2 = th.rand([5])
v3 = th.rand([5])
M1 = th.rand([2,5])
M2 = th.rand([2,5])
M3 = th.rand([2,5])

print(f'Apilado de vectores sobre dimensión 0: {th.stack([v1, v2, v3], dim=0).shape}')
print(f'Apilado de vectores sobre dimensión 1: {th.stack([v1, v2, v3], dim=1).shape}')
print(f'Apilado de matrices sobre dimensión 0: {th.stack([M1, M2, M3], dim=0).shape}')
print(f'Apilado de matrices sobre dimensión 1: {th.stack([M1, M2, M3], dim=1).shape}')
print(f'Apilado de matrices sobre dimensión 2: {th.stack([M1, M2, M3], dim=2).shape}')

Apilado de vectores sobre dimensión 0: torch.Size([3, 5])
Apilado de vectores sobre dimensión 1: torch.Size([5, 3])
Apilado de matrices sobre dimensión 0: torch.Size([3, 2, 5])
Apilado de matrices sobre dimensión 1: torch.Size([2, 3, 5])
Apilado de matrices sobre dimensión 2: torch.Size([2, 5, 3])


### Producto de matrices
Para realizar el producto matricial de dos tensores usamos el operador `@` o la función `matmul`. Su comportamiento depende del grado de los tensores: con dos vectores devuelve el producto interno, con una matriz y un vector el producto matriz-vector, con dos matrices el producto matricial y con tensores de grado mayor interpreta las dimensiones iniciales como un lote de matrices y difunde sobre ellas.

In [51]:
M4 = th.rand(5, 4)
A3 = th.rand(10, 2, 5)   # lote de 10 matrices de 2x3

print(f'v1={v1.shape}, v2={v2.shape}, M1={M1.shape}, M4={M4.shape}, A3={A3.shape}')
print(f'v1 @ v2 -> {(v1 @ v2).shape} (escalar)')
print(f'M1 @ v1 -> {(M1 @ v1).shape}')
print(f'v1@ M4 -> {(v1 @ M4).shape}')
print(f'M1 @ M4 -> {(M1 @ M4).shape}')
print(f'A3 @ M4   -> {(A3 @ M4).shape}')

v1=torch.Size([5]), v2=torch.Size([5]), M1=torch.Size([2, 5]), M4=torch.Size([5, 4]), A3=torch.Size([10, 2, 5])
v1 @ v2 -> torch.Size([]) (escalar)
M1 @ v1 -> torch.Size([2])
v1@ M4 -> torch.Size([4])
M1 @ M4 -> torch.Size([2, 4])
A3 @ M4   -> torch.Size([10, 2, 4])


Adicionalmente, PyTorch ofrece la función `dot` para el producto interno de dos vectores, `mv` para el producto matriz-vector, `mm` para el producto de dos matrices, `bmm` para el producto de lotes de matrices y `outer` para el producto externo. A diferencia de el operador `@` o la función `matmul`, estas funciones no permiten operandos que no cumplan con el grado correspondiente.

Nota que el operador `*` multiplica elemento a elemento, mientras que el operador `@` realiza la multiplicación matricial.

## Operaciones de reducción
También se puede reducir una dimensión de un tensor con distintas funciones (y métodos equivalentes), tales como suma (`sum`), producto (`prod`) y promedio (`mean`):

In [52]:
x_red = th.rand([3, 10])

print(f'x_red={x_red}\n')
print(f'Valor máximo = {th.max(x_red)}')
print(f'Valor mínimo = {th.min(x_red)}')
print(f'Índice del valor máximo = {th.argmax(x_red)}')
print(f'Índice del valor mínimo = {th.argmin(x_red)}')
print(f'Suma = {th.sum(x_red)}')
print(f'Producto = {th.prod(x_red)}')
print(f'Promedio = {th.mean(x_red)}')

x_red=tensor([[0.2016, 0.9735, 0.3950, 0.0409, 0.3327, 0.1533, 0.8309, 0.5434, 0.8572,
         0.9072],
        [0.5377, 0.1980, 0.0648, 0.2048, 0.9167, 0.2226, 0.2512, 0.2306, 0.7336,
         0.5454],
        [0.5502, 0.7535, 0.4755, 0.5122, 0.6981, 0.6022, 0.9603, 0.1242, 0.0910,
         0.9635]])

Valor máximo = 0.9734565019607544
Valor mínimo = 0.04090088605880737
Índice del valor máximo = 1
Índice del valor mínimo = 3
Suma = 14.871899604797363
Producto = 1.683811103785418e-13
Promedio = 0.4957299828529358


Cuando no se especifica una dimensión, `argmax` y `argmin` devuelven el índice sobre el
tensor aplanado. Para obtener la posición por dimensión se puede usar `unravel_index`.

In [53]:
idx = th.argmax(x_red)
pos = th.unravel_index(idx, x_red.shape)

print(f'Índice sobre el tensor aplanado: {idx}')
print(f'Índice por dimensión: {pos}, elemento: {x_red[pos]:.4f}')

Índice sobre el tensor aplanado: 1
Índice por dimensión: (tensor(0), tensor(1)), elemento: 0.9735


Es posible especificar la dimensión en el que se desea realizar la reducción. Las funciones/métodos `min` y `max` devuelven un par de tensores: el primero es el de valores mínimos/máximos y el segundo es el de los índices de estos valores.

In [54]:
print(f'x_red={x_red}\n')
print(f'Valor máximo sobre dimensión 0: {x_red.max(dim=0)}')
print(f'Valor máximo sobre dimensión 1: {x_red.max(dim=1)}')
print(f'Promedio sobre dimensión 0: {x_red.mean(dim=0)}')
print(f'Promedio sobre dimensión 1: {x_red.mean(dim=1)}')

x_red=tensor([[0.2016, 0.9735, 0.3950, 0.0409, 0.3327, 0.1533, 0.8309, 0.5434, 0.8572,
         0.9072],
        [0.5377, 0.1980, 0.0648, 0.2048, 0.9167, 0.2226, 0.2512, 0.2306, 0.7336,
         0.5454],
        [0.5502, 0.7535, 0.4755, 0.5122, 0.6981, 0.6022, 0.9603, 0.1242, 0.0910,
         0.9635]])

Valor máximo sobre dimensión 0: torch.return_types.max(
values=tensor([0.5502, 0.9735, 0.4755, 0.5122, 0.9167, 0.6022, 0.9603, 0.5434, 0.8572,
        0.9635]),
indices=tensor([2, 0, 2, 2, 1, 2, 2, 0, 0, 2]))
Valor máximo sobre dimensión 1: torch.return_types.max(
values=tensor([0.9735, 0.9167, 0.9635]),
indices=tensor([1, 4, 9]))
Promedio sobre dimensión 0: tensor([0.4298, 0.6416, 0.3118, 0.2526, 0.6492, 0.3260, 0.6808, 0.2994, 0.5606,
        0.8054])
Promedio sobre dimensión 1: tensor([0.5236, 0.3906, 0.5731])


Por otro lado, tenemos la función (y el método) `sort` que ordena un tensor. Al igual que `min` y `max`, cuando se especifica una dimensión `sort` regresa tanto el tensor de valores como el tensor de índices. Si solo requerimos los índices, podemos usar la función `argsort`.

Por otro lado, tenemos la función (y el método) `sort`, que ordena los elementos a lo largo de una dimensión (la última por defecto) y devuelve tanto el tensor de valores ordenados como el de los índices que ocupaban originalmente. Si solo requerimos los índices, podemos usar la función `argsort`.

In [55]:
xsort = th.randint(low=-10, high=10, size=(3, 4))

orden_desc = th.sort(xsort, descending=True)
orden_asc = th.sort(xsort, descending=False)
orden_dim0 = th.sort(xsort, descending=False, dim=0)

print(f'xsort={xsort}\n')
print(f'Ordenado de mayor a menor (última dimensión):{orden_desc.values}')
print(f'Índices correspondientes:{orden_desc.indices}\n')
print(f'Ordenado de menor a mayor (última dimensión):{orden_asc.values}')
print(f'Índices correspondientes:{orden_asc.indices}\n')
print(f'Ordenado de menor a mayor sobre la dimensión 0:{orden_dim0.values}')
print(f'Índices correspondientes:{orden_dim0.indices}\n')
print(f'Solo los índices, con argsort:{th.argsort(xsort, descending=False)}')

xsort=tensor([[-2,  5, -5, -3],
        [-9, -8, -6,  1],
        [-8,  2, -5, -4]])

Ordenado de mayor a menor (última dimensión):tensor([[ 5, -2, -3, -5],
        [ 1, -6, -8, -9],
        [ 2, -4, -5, -8]])
Índices correspondientes:tensor([[1, 0, 3, 2],
        [3, 2, 1, 0],
        [1, 3, 2, 0]])

Ordenado de menor a mayor (última dimensión):tensor([[-5, -3, -2,  5],
        [-9, -8, -6,  1],
        [-8, -5, -4,  2]])
Índices correspondientes:tensor([[2, 3, 0, 1],
        [0, 1, 2, 3],
        [0, 2, 3, 1]])

Ordenado de menor a mayor sobre la dimensión 0:tensor([[-9, -8, -6, -4],
        [-8,  2, -5, -3],
        [-2,  5, -5,  1]])
Índices correspondientes:tensor([[1, 1, 1, 2],
        [2, 2, 0, 0],
        [0, 0, 2, 1]])

Solo los índices, con argsort:tensor([[2, 3, 0, 1],
        [0, 1, 2, 3],
        [0, 2, 3, 1]])


## Uso de GPUs
En muchos casos, el uso de GPUs reduce significativamente el tiempo de entrenamiento de los modelos basados en redes neuronales profundas. Por lo mismo, los marcos de trabajo como PyTorch permiten crear o copiar tensores y ejecutar las operaciones tensoriales en uno o más CPUs/GPUs e incluso en distintas computadoras. Además, ofrecen herramientas para controlar de manera flexible dónde se crea o copia cada tensor y dónde se ejecuta cada operación. Por ello, cada instancia de la clase `Tensor` cuenta con el elemento `.device` que indica el dispositivo en el que se encuentra almacenado. Por defecto, si hay al menos uno disponible, los tensores se crean en el GPU.

In [56]:
!nvidia-smi

Sun Aug 23 17:41:41 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   63C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

Para saber si algún GPU está disponible, contamos con la función `is_available` del módulo de `cuda`.

In [57]:
if th.cuda.is_available():
  print('Hay GPUs disponibles')
else:
  print('No hay GPUs disponibles. Las siguientes celdas se ejecutarán en CPU.')

Hay GPUs disponibles


Por defecto, los tensores se crean en CPU.

In [58]:
xcpu = th.rand((100, 100))
print(f'El tensor xcpu se encuentra en {xcpu.device}')

El tensor xcpu se encuentra en cpu


Podemos especificar explícitamente dónde queremos crear una instancia de `Tensor` usando el argumento `device` que tienen muchas funciones de PyTorch. Por ej. si queremos crear el tensor en GPU pasamos la cadena `cuda` o `cuda:0`, donde el valor después de los dos puntos en esta última forma especifica el índice del GPU (es distinto de 0 cuando tenemos múltiples GPUs disponibles).

In [59]:
disp = th.device('cuda' if th.cuda.is_available() else 'cpu')
xgpu = th.rand((100, 100), device=disp)
print(f'Tensor xgpu creado en {xgpu.device}')

Tensor xgpu creado en cuda:0


Las operaciones que se realicen con estos tensores se correrán en el GPU y los tensores resultantes estarán en este mismo dispositivo.

In [60]:
ygpu = th.rand((100, 100), device=disp)
(xgpu + ygpu).device

device(type='cuda', index=0)

Sin embargo, cuando realizamos una operación con tensores que se encuentran en dispositivos distintos, PyTorch lanza un error!)

In [61]:
try:
  xgpu + xcpu
except RuntimeError as err:
  print(f'xgpu + xcpu: {err}')

xgpu + xcpu: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!


Por lo tanto, para poder realizar esta operación es necesario transferir uno de los tensores a otro dispositivo. En PyTorch esto lo llevamos a cabo con el método `to`.

In [62]:
xcpugpu = xcpu.to(disp)
(xcpugpu + xgpu).device, xcpugpu.device

(device(type='cuda', index=0), device(type='cuda', index=0))

Comparémos ahora los tiempos de ejecución en CPU y GPU de una multiplicación de dos matrices.

Creamos las matrices en CPU y GPU:

In [63]:
n = 10000
Acpu, Bcpu = th.rand((n, n)), th.rand((n, n))
Agpu, Bgpu = Acpu.to(disp), Bcpu.to(disp)

Tiempo de multiplicación en CPU:

In [64]:
%%timeit -n1 -r3
res = Acpu @ Bcpu

16.8 s ± 178 ms per loop (mean ± std. dev. of 3 runs, 1 loop each)


En GPU:

In [65]:
%%timeit -n1 -r3
res = Agpu @ Bgpu
th.cuda.synchronize()

600 ms ± 30.5 ms per loop (mean ± std. dev. of 3 runs, 1 loop each)


### Ejercicio
Calcula el producto de cada matriz de $400 \times 1000$ en un tensor aleatorio $A$ de tamaño $500 \times 400 \times 1000$ con la transpuesta de un tensor aleatorio $B$ de tamaño $200 \times 1000$. Concatena el resultado a un tensor aleatorio $C$ con el mismo número de columnas que el resultado de la operación anterior. Compara los tiempos de ejecución de esta operación en GPU y CPU.