<a href="https://colab.research.google.com/github/gibranfp/CursoAprendizajeProfundo/blob/2025-1/notebooks/3a_celda_recurrente.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.random.seed(123)
from collections import Counter

textos = ['un bolillo para el susto',
          'tembló el 19 de septiembre']
n_docs = len(textos)

In [2]:
tokens = [t.split() for t in textos]
max_sec = len(tokens[0])
print(tokens[0])
print(tokens[1])

['un', 'bolillo', 'para', 'el', 'susto']
['tembló', 'el', '19', 'de', 'septiembre']


In [3]:
voc = Counter([p for t in tokens for p in t])

i2p = {i:p for i,(p,f) in enumerate(voc.most_common())}
p2i = {p:i for i,(p,f) in enumerate(voc.most_common())}

tam_voc = len(i2p)

indsecs = np.array([[p2i[p] for p in t] for t in tokens])

print(tam_voc)
print(indsecs)

9
[[1 2 3 0 4]
 [5 0 6 7 8]]


In [4]:
ohesecs = np.zeros((n_docs, max_sec, tam_voc))

for i in range(ohesecs.shape[0]):
  for j in range(ohesecs.shape[1]):
    ohesecs[i, j, indsecs[i, j]] = 1

print(ohesecs)

[[[0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1.]]]


In [5]:
tam_edo = 10

h = np.zeros((tam_edo, 1))

k = 1 / tam_edo
Wih = np.random.uniform(-np.sqrt(k), np.sqrt(k), size=(tam_voc, tam_edo))
Whh = np.random.uniform(-np.sqrt(k), np.sqrt(k), size=(tam_edo, tam_edo))
b = np.random.uniform(-np.sqrt(k), np.sqrt(k), size=(tam_edo, 1))

print(Wih)
print(Whh)
print(b)
print(h)

[[ 0.12425802 -0.13525736 -0.17275431  0.03245431  0.13880436 -0.04863174
   0.30406198  0.11689659 -0.01205972 -0.06823087]
 [-0.09918293  0.14486375 -0.03885032 -0.27848415 -0.06448247  0.15052151
  -0.20080986 -0.20526233  0.01995484  0.02012953]
 [ 0.08500263  0.22100007  0.14195801  0.07021743  0.14068555 -0.11197061
  -0.08741253 -0.17186142 -0.13046669  0.08283657]
 [-0.25797549 -0.04193106 -0.04372623 -0.00399389 -0.04690904 -0.11873643
  -0.04657952  0.24880115  0.28091146  0.00116162]
 [ 0.07839473 -0.24310427 -0.11555881 -0.05386863  0.23167425 -0.15782588
  -0.01073007  0.30709497  0.01232347  0.07140077]
 [-0.2399355   0.20639604  0.06518095  0.02850351 -0.09944488 -0.12388489
  -0.05247976  0.11466467  0.23745976  0.00659166]
 [ 0.10708344  0.05435105  0.07899591  0.11048306  0.21651637 -0.26361064
   0.16676767 -0.16211962 -0.19339038  0.0458258 ]
 [-0.25569386  0.24370208  0.08047932  0.14130091 -0.30602676  0.05972396
   0.03591411 -0.21569286 -0.21941747  0.12366373]


In [6]:
print(h)

x = ohesecs[0, 0].reshape(-1, 1)
h = np.tanh(Wih.T @ x + Whh.T @ h + b)

print(x)
print(h)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[-0.27758571]
 [ 0.27529654]
 [-0.11487702]
 [-0.1703128 ]
 [-0.3471212 ]
 [ 0.23216107]
 [-0.45949731]
 [-0.0504067 ]
 [ 0.00282351]
 [-0.21565438]]


In [7]:
x = ohesecs[0, 1].reshape(-1, 1)
h = np.tanh(Wih.T @ x + Whh.T @ h + b)

print(h)

[[-0.18229209]
 [ 0.33467929]
 [ 0.20728909]
 [-0.00235884]
 [-0.37471099]
 [ 0.10200451]
 [-0.16481057]
 [-0.13317152]
 [-0.11940297]
 [-0.12936611]]


In [8]:
x = ohesecs[0, 2].reshape(-1, 1)
h = np.tanh(Wih.T @ x + Whh.T @ h + b)

print(h)

[[-0.50380956]
 [ 0.1327796 ]
 [-0.20902012]
 [-0.03965543]
 [-0.5260194 ]
 [ 0.11778588]
 [-0.11667681]
 [ 0.39424248]
 [ 0.25323813]
 [-0.16903096]]


In [9]:
x = ohesecs[0, 3].reshape(-1, 1)
h = np.tanh(Wih.T @ x +  Whh.T @ h + b)

print(h)

[[-0.17424923]
 [ 0.00118325]
 [-0.06773097]
 [-0.20441229]
 [-0.27181108]
 [ 0.14336168]
 [ 0.11833813]
 [ 0.36545911]
 [ 0.15757325]
 [-0.30752426]]


In [10]:
x = ohesecs[0, 4].reshape(-1, 1)
h = np.tanh(Wih.T @ ohesecs[0, 4].reshape(-1, 1) + Whh.T @ h + b)

print(h)

[[-0.27060999]
 [ 0.03785503]
 [-0.02104424]
 [-0.18669299]
 [-0.12916769]
 [-0.11505438]
 [-0.17503436]
 [ 0.50462974]
 [ 0.01164821]
 [-0.14521163]]


In [11]:
class CeldaRecurrente:
  def __init__(self, tam_ent, tam_edo):
    self.input_size = tam_ent
    self.hidden_size = tam_edo

    k = 1 / tam_edo
    self.W = np.random.uniform(-np.sqrt(k), np.sqrt(k),
                               size=(tam_edo + tam_voc, tam_edo))
    self.b = np.random.uniform(-np.sqrt(k), np.sqrt(k),
                               size=(tam_edo, 1))

  def __call__(self, x, h):
    xh = np.concatenate((x.reshape(-1, 1), h), axis=0)
    return np.tanh(self.W.T @ xh + self.b)

In [12]:
def ejecuta_celda(celda, X, h0):
  # Calculamos los estados para todas las entradas
  # del primer ejemplo
  for i in range(X.shape[0]):
    print(f'Ejemplo {i}')
    h = h0 # primer estado con ceros
    print(f'\tEstado 0: {h.reshape(-1)}')
    for t in range(X.shape[1]):
      print(f'\tEntrada {t}: {X[i, t]}')
      h = celda(X[i, t], h)
      print(f'\tEstado {t + 1}: {h.reshape(-1)}')

rec = CeldaRecurrente(tam_voc, tam_edo)
ejecuta_celda(rec, ohesecs, np.zeros((tam_edo, 1)))

Ejemplo 0
	Estado 0: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
	Entrada 0: [0. 1. 0. 0. 0. 0. 0. 0. 0.]
	Estado 1: [-0.0759335  -0.08485358  0.22996836  0.17487778 -0.1986069  -0.09994107
 -0.3664835  -0.16142094  0.04018256  0.02065069]
	Entrada 1: [0. 0. 1. 0. 0. 0. 0. 0. 0.]
	Estado 2: [-0.4016619   0.06029743  0.15565653  0.25876275  0.24521503 -0.28031747
 -0.10754939  0.13020968 -0.338656   -0.00040447]
	Entrada 2: [0. 0. 0. 1. 0. 0. 0. 0. 0.]
	Estado 3: [-0.56882713 -0.46993657  0.29491674 -0.02776678  0.06797312 -0.31030028
 -0.4119208   0.34701066 -0.27164639  0.30664792]
	Entrada 3: [1. 0. 0. 0. 0. 0. 0. 0. 0.]
	Estado 4: [-0.25864153 -0.61467619  0.60491373  0.26232086  0.29968149 -0.07874826
 -0.39924809  0.19577913 -0.0546648  -0.07383566]
	Entrada 4: [0. 0. 0. 0. 1. 0. 0. 0. 0.]
	Estado 5: [-0.4364386  -0.30670577  0.70127047 -0.01428004 -0.28900731 -0.08953324
  0.19283268  0.13413254 -0.09338661  0.53283121]
Ejemplo 1
	Estado 0: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
	Entrada 0: [0. 0. 

In [13]:
class CeldaRecurrenteSep:
  def __init__(self, tam_ent, tam_edo):
    self.input_size = tam_ent
    self.hidden_size = tam_edo

    k = 1 / tam_edo
    self.Wih = np.random.uniform(-np.sqrt(k), np.sqrt(k),
                                 size=(tam_voc, tam_edo))
    self.Whh = np.random.uniform(-np.sqrt(k), np.sqrt(k),
                                 size=(tam_edo, tam_edo))
    self.b = np.random.uniform(-np.sqrt(k), np.sqrt(k),
                               size=(tam_edo, 1))

  def __call__(self, x, h):
    x = x.reshape(-1, 1)
    return np.tanh(self.Wih.T @ x + self.Whh @ h + self.b)

recsep = CeldaRecurrenteSep(tam_voc, tam_edo)
ejecuta_celda(recsep, ohesecs, np.zeros((tam_edo, 1)))

Ejemplo 0
	Estado 0: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
	Entrada 0: [0. 1. 0. 0. 0. 0. 0. 0. 0.]
	Estado 1: [-0.30274589 -0.14584702  0.21775718 -0.16328027 -0.06657082  0.03680834
 -0.08233328 -0.17864147 -0.36808185 -0.06613953]
	Entrada 1: [0. 0. 1. 0. 0. 0. 0. 0. 0.]
	Estado 2: [-0.0241193  -0.10601396  0.19587479  0.04063571 -0.04728349  0.31474752
  0.44448087  0.00161761 -0.36936394 -0.41361203]
	Entrada 2: [0. 0. 0. 1. 0. 0. 0. 0. 0.]
	Estado 3: [ 0.00715866 -0.37560026 -0.15369939 -0.48217921 -0.2906317  -0.22361022
  0.45639075 -0.34818426 -0.29361202 -0.39570424]
	Entrada 3: [1. 0. 0. 0. 0. 0. 0. 0. 0.]
	Estado 4: [-0.12245958 -0.20597719  0.07580284 -0.28606704  0.06516598 -0.35971193
  0.2352521  -0.0822994  -0.5850762  -0.72220702]
	Entrada 4: [0. 0. 0. 0. 1. 0. 0. 0. 0.]
	Estado 5: [-0.24344363 -0.14666431  0.14468528 -0.38389906 -0.39166732 -0.00362555
  0.32971018 -0.19639911 -0.6504046  -0.6084197 ]
Ejemplo 1
	Estado 0: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
	Entrada 0: [0. 0. 

In [14]:
import torch as th

recth = th.nn.RNNCell(tam_voc, tam_edo)
oheth = th.from_numpy(ohesecs).type(th.float32)

ejecuta_celda(recth, oheth, th.zeros((tam_edo)))

Ejemplo 0
	Estado 0: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
	Entrada 0: tensor([0., 1., 0., 0., 0., 0., 0., 0., 0.])
	Estado 1: tensor([ 0.4223, -0.2212,  0.0495,  0.3192, -0.1657,  0.2840,  0.3125,  0.0158,
         0.6095, -0.0248], grad_fn=<ViewBackward0>)
	Entrada 1: tensor([0., 0., 1., 0., 0., 0., 0., 0., 0.])
	Estado 2: tensor([ 3.7261e-01, -3.1463e-02, -2.5538e-01,  2.2709e-04,  3.3464e-02,
         2.8348e-01, -2.2390e-01,  2.5217e-01,  2.0497e-01,  6.8456e-02],
       grad_fn=<ViewBackward0>)
	Entrada 2: tensor([0., 0., 0., 1., 0., 0., 0., 0., 0.])
	Estado 3: tensor([ 0.6840, -0.2070,  0.3103, -0.3129,  0.2009,  0.6734, -0.0842,  0.3179,
         0.4567, -0.2387], grad_fn=<ViewBackward0>)
	Entrada 3: tensor([1., 0., 0., 0., 0., 0., 0., 0., 0.])
	Estado 4: tensor([ 0.2408, -0.1091, -0.0986,  0.2509, -0.4163,  0.6446, -0.0058, -0.1346,
         0.3032, -0.0969], grad_fn=<ViewBackward0>)
	Entrada 4: tensor([0., 0., 0., 0., 1., 0., 0., 0., 0.])
	Estado 5: tensor([ 0.6413

In [15]:
rnn = th.nn.RNN(tam_voc, tam_edo) # Interfaz de más alto nivel que RNNCell.
                                  # puede procesar varios pasos y ejemplos
                                  # a la vez. Además, se pueden definir celdas
                                  # apiladas y bidireccionales
outputs, h = rnn(oheth)

In [16]:
lstm = th.nn.LSTM(tam_voc, tam_edo, batch_first=True) # Similar a la anterior
                                                      # para celda LSTM
output, (h,c) = lstm(oheth)

In [17]:
gru = th.nn.GRU(tam_voc, tam_edo, batch_first=True) # Similar a la anterior
                                                    # para celda GRU
output, h = gru(oheth)

In [18]:
outputs

tensor([[[ 0.3969, -0.2635, -0.1929,  0.2182,  0.5295, -0.0632, -0.4590,
           0.3251, -0.0249, -0.1758],
         [ 0.2629, -0.3888, -0.5001,  0.3447,  0.1492, -0.0696, -0.3322,
           0.2772, -0.3505, -0.0957],
         [ 0.4536, -0.3628, -0.3863,  0.1550,  0.2337, -0.3457, -0.2434,
           0.2668,  0.1095, -0.2488],
         [ 0.5636, -0.2407, -0.4525,  0.1052,  0.3835, -0.1135, -0.5670,
           0.1404, -0.0296,  0.2440],
         [ 0.5247, -0.3616, -0.5930,  0.1632,  0.4371, -0.3750, -0.6264,
           0.2227, -0.4125, -0.2998]],

        [[ 0.1653, -0.1780, -0.1581,  0.0785,  0.3746, -0.0013, -0.1313,
           0.4277, -0.0530,  0.1578],
         [ 0.5437, -0.1489, -0.3903,  0.1175,  0.4877, -0.3181, -0.5182,
           0.2104,  0.2256,  0.3984],
         [ 0.5388, -0.2974, -0.4959,  0.1044,  0.6355, -0.3730, -0.1032,
          -0.1402,  0.1149,  0.3175],
         [ 0.1825, -0.0132, -0.3667,  0.3346,  0.5587, -0.0982, -0.1433,
           0.0905, -0.0555,  0.0675],